---
# yamllint disable rule:line-length
name: Test Ansible roles with Molecule
description: Run Molecule to test Ansible roles
author: Open Microscopy Environment

branding:
  icon: server
  color: yellow

inputs:
  scenario:
    description: Molecule scenario name
    required: false
    default: default
  subdir:
    description: Subdirectory to run molecule in if not the top level
    required: false
    default: ./
  manage-virtualenv:
    description: >
      If true create virtualenv and install dependencies, otherwise user is
      responsible for installing dependencies
    required: false
    default: "true"
  ome-ansible-molecule-version:
    description: The version of ome-ansible-molecule
    required: false
    default: "0.5.*"

runs:
  using: "composite"
  steps:
    - name: Create virtualenv
      run: |
        if [[ "${{ inputs.manage-virtualenv }}" == "true" ]]; then
          python3 -mvenv ~/venv
          ~/venv/bin/pip install -U pip
          ~/venv/bin/pip install "ome-ansible-molecule==${{ inputs.ome-ansible-molecule-version }}"
          echo PATH=~/venv/bin:$PATH >> $GITHUB_ENV
          echo VIRTUAL_ENV=~/venv >> $GITHUB_ENV
        fi
      shell: bash
    - name: Run molecule
      run: |
        cd "${{ inputs.subdir }}"
        molecule test -s "${{ inputs.scenario }}"
      shell: bash
